//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChat.Models
{
    public partial class AutoResponseRule
    {
        public int Id { get; set; }
        public string MsgType { get; set; }
        public string RequestPattern { get; set; }
        public string ResponseType { get; set; }
        public string ResponseContent { get; set; }
    }
}
